version: '3'
services:
  app:
    build: ./docker/app
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_ALLOW_EMPTY_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
