version: "3.0"
services:

  web:
    image: nginx:1.20-alpine
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./laravel:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  app:
    build: ./docker/php
    volumes:
      - ./laravel:/work

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

  front_app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        - TZ=${TZ}
    volumes:
      - ./nuxt:/var/www/nuxt
    ports:
      - ${FRONT_PORT}:3000
    links:
      - web
    depends_on:
      - web
    tty: true

volumes:
  db-store:
